fragment CzechParts on Czech {
  reasonsTitle
  reasons {
    __typename
    reasonTitle
    reasonText
  }
  methodTitle
  methodText
  resolutionTitle
  resolutions {
    __typename
    resolutionTitle
    resolutionText
  }
  processTitle
  processSteps {
    __typename
    processStepText
  }
  aboutTitle
  aboutText
  placeLookTitle
  reviewsTitle
  reviews {
    __typename
    reviewName
    reviewText
  }
  faqTitle
  faq {
    __typename
    faqTitle
    faqText
  }
  videosTitle
  contactTitle
  email
  phone
  price
}

fragment EnglishParts on English {
  reasonsTitle
  reasons {
    __typename
    reasonTitle
    reasonText
  }
  methodTitle
  methodText
  resolutionTitle
  resolutions {
    __typename
    resolutionTitle
    resolutionText
  }
  processTitle
  processSteps {
    __typename
    processStepText
  }
  aboutTitle
  aboutText
  placeLookTitle
  reviewsTitle
  reviews {
    __typename
    reviewName
    reviewText
  }
  faqTitle
  faq {
    __typename
    faqTitle
    faqText
  }
  videosTitle
  contactTitle
  email
  phone
  price
}

fragment ImagesParts on Images {
  introImages {
    __typename
    introImage
  }
}
