fragment PageParts on Page {
  reasonsTitle
  reasons {
    __typename
    reasonTitle
    reasonText
  }
  methodTitle
  methodText
  resolutionTitle
  resolutions {
    __typename
    resolutionTitle
    resolutionText
  }
  processTitle
  processSteps {
    __typename
    processStepText
  }
  aboutTitle
  aboutText
  reviewsTitle
  reviews {
    __typename
    reviewName
    reviewText
  }
}
